<?php

namespace CYA\YogaBundle\Repository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
